export const ObjectConstants = {
    FETCH: 'OBJECT_FETCH',
    PUT: 'OBJECT_PUT',
    DELETE: 'OBJECT_DELETE',
    CLEAR_STATE: 'OBJECT_CLEAR_STATE',
    ADD_IMAGE: 'OBJECT_ADD_IMAGE',
    DELETE_IMAGE: 'OBJECT_DELETE_IMAGE',
    SET_ACTIVE_IMAGE: 'OBJECT_SET_ACTIVE_IMAGE'
};
