export const DotConstants = {
  FETCH: 'DOT_FETCH',
  PUT: 'DOT_PUT',
  DELETE: 'DOT_DELETE',
  CLEAR_STATE: 'DOT_CLEAR_STATE',
  ADD_IMAGE: 'DOT_ADD_IMAGE',
  DELETE_IMAGE: 'DOT_DELETE_IMAGE',
  SET_ACTIVE_IMAGE: 'DOT_SET_ACTIVE_IMAGE'
};
