export const PathConstants = {
    FETCH: 'PATH_FETCH',
    PUT: 'PATH_PUT',
    DELETE: 'PATH_DELETE',
    CLEAR_STATE: 'PATH_CLEAR_STATE',
    ADD_IMAGE: 'PATH_ADD_IMAGE',
    DELETE_IMAGE: 'PATH_DELETE_IMAGE',
    SET_ACTIVE_IMAGE: 'PATH_SET_ACTIVE_IMAGE'
};
